port: 7065

# Run "make generate_cert" to generate these files.
cert_file: /Users/kevin/src/github.com/kevinburke/go-html-boilerplate/cert.pem
key_file: /Users/kevin/src/github.com/kevinburke/go-html-boilerplate/key.pem
