
[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"

[[constraint]]
  name = "github.com/kevinburke/handlers"
  version = "0.35.0"

[[constraint]]
  name = "github.com/kevinburke/nacl"
  version = "0.5.0"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "1.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
